### ISSUE TITLE
Driver patching fails with "patch line 9 contains NUL byte" - custom driver file not created

### ISSUE THREAD

**Issue by pieewiee** [anomixer/proxmox-vgpu-installer#2]
## Description

The NVIDIA vGPU driver patching process fails when attempting to create a custom patched driver file. The patch command encounters NUL bytes and the expected custom driver file is never created.

## System Information

- **Proxmox Version:** 9.0.10
- **Kernel:** 6.14.11-2-pve  
- **GPU:** NVIDIA RTX 4500 Ada Generation
- **Driver Version:** NVIDIA-Linux-x86_64-570.158.02-vgpu-kvm.run
- **Patch File:** 570.158.02.patch
- **vgpu_unlock-rs:** Latest (built successfully)
- **Script Version:** 1.3

## Steps to Reproduce

1. Run the Proxmox vGPU installer script
2. Choose "New vGPU installation" 
3. Complete Step 1 and reboot
4. Run Step 2 and select driver version 18.3 (570.158.02)
5. Driver downloads successfully with valid MD5 checksum
6. Patching command executes: `./NVIDIA-Linux-x86_64-570.158.02-vgpu-kvm.run --apply-patch /root/proxmox-vgpu-installer/vgpu-proxmox/570.158.02.patch`

## Expected Behavior

- Patch should apply successfully
- Custom driver file `NVIDIA-Linux-x86_64-570.158.02-vgpu-kvm-custom.run` should be created
- Installation should proceed to driver installation

## Actual Behavior

- Patching fails with error: `/usr/bin/patch: **** patch line 9 contains NUL byte`
- Custom driver file is not created
- Next step fails: `./NVIDIA-Linux-x86_64-570.158.02-vgpu-kvm-custom.run: No such file or directory`

## Error Logs

```
[+] Patching driver
Executing command: ./NVIDIA-Linux-x86_64-570.158.02-vgpu-kvm.run --apply-patch /root/proxmox-vgpu-installer/vgpu-proxmox/570.158.02.patch
[+] Installing patched driver
Executing command: ./NVIDIA-Linux-x86_64-570.158.02-vgpu-kvm-custom.run --dkms -s
```

From debug.log:
```
/usr/bin/patch: **** patch line 9 contains NUL byte
./proxmox-installer.sh: line 89: ./NVIDIA-Linux-x86_64-570.158.02-vgpu-kvm-custom.run: No such file or directory
```

## Additional Information

- The original driver file downloads correctly and passes MD5 verification
- vgpu_unlock-rs builds successfully with only 1 warning about unused struct
- RTX 4500 Ada Generation was manually added to gpu_info.db
- The patch file exists in the vgpu-proxmox directory

**Comment by anomixer** [comment]
Hi,

Thanks for the feedback. However, this should be not an issue.

Your 4500 Ada Generation is not a vGPU capable card, nor it can be patched by vgpu_unlock.
This card already listed in gpu_info.db by original author.
So your card can only pass-through to one single VM.

By the way, the script should show the following messages (if you didn't modify the script ;) ):

...
[+] Installing packages
[+] Setup pve-nvidia-vgpu-helper
[*] Found one Nvidia GPU in your system

NVIDIA RTX 4500 Ada Generation is not vGPU capable

[!] You don't have a vGPU capable card in your system
Exiting  script.
...

**Comment by pieewiee** [comment]
Hi there!

Oops, my bad! 😅 You're absolutely right about the RTX 4500 Ada Generation. I got a bit overzealous and manually added it to the database thinking "surely this professional card should work" - classic case of wishful thinking over actual compatibility! 

Thanks for the reality check and for pointing out that it's already correctly listed in the original database as non-vGPU capable. I should have trusted the database instead of trying to "fix" what wasn't broken.

Good news though - I actually have an **NVIDIA GeForce RTX 2060 SUPER** laying around that I can swap in. Looking at the database, this one is properly listed as:
- vGPU: Yes 
- Driver: 17;16
- Chip: TU106

So this should actually work with vgpu_unlock! 🎉

Will keep you posted on how it goes!

Thanks again for the quick response and for maintaining this awesome project.

Cheers!

**Comment by pieewiee** [comment]
Swapped to RTX 2060 SUPER (Device ID: 1f47) - properly detected as vGPU capable. Same exact error occurs:

```
/usr/bin/patch: **** patch line 9 contains NUL byte
./NVIDIA-Linux-x86_64-570.158.02-vgpu-kvm-custom.run: No such file or directory
```

This confirms the 570.158.02.patch file is corrupted. The script incorrectly reports success even though patching fails.

RTX 2060 SUPER supports driver versions 17;16 according to database. Should I try driver 18.4 (570.172.07) or stick to officially supported 17.x versions?

The vGPU detection and database work correctly - this is purely a patch file corruption issue.

**Comment by anomixer** [comment]
Hi,

The patch v2.8 in Debian 13 (Proxmox 9) cause the NUL byte error.
But it won't happen on patch v2.7.6 in Debian 12 (Proxmox 8), Ubuntu.
So it's not patch file or nvidia driver issue.

I've update my script to install the previous patch version to make the patch work.
Due to there's still no 19.1 patch file released currently, you can try install 18.x and 19.0 now.

**Comment by Porkki** [comment]
This time the driver installation went through but I got warning message that said 
`WARNING: The 'NVIDIA Proprietary' kernel modules are incompatible with the GPU(s) detected on this system. They will be installed anyway, but are not expected to work.`

Still after reboot mdev devices does not show, not in resource mapping or with mdevctl types command. Any suggestion on what to try next?

**Comment by anomixer** [comment]
ok

**Comment by anomixer** [comment]
Hi Guys,

FYI. Check the readme of this repo: https://github.com/PTHyperdrive/proxmox-vgpu-installer

The content in the section of Changes:
-------------------------------------------------------------------
Added driver versions 16
16.0
16.1
16.2
16.3
16.4 / 16.5
16.7
16.8
16.9 !!! USE THIS IF YOU ARE ON PASCAL OR OLDER !!!

Added driver versions 17
17.0
17.1
17.3
17.4
17.5
17.6 (Only Native vGPU support)

Added driver versions 18
18.0
18.1 (Only Native vGPU support)
-------------------------------------------------------------------

That said the NVIDIA driver 18.1+ version *should* support Native vGPU only.
I doubt the 19.x also works for Native vGPU, too.

**Comment by ivan-danilov** [comment]
@anomixer I have Tesla P4, which is Pascal same as GTX 1080. I saw the recommendation to use 16.9, but there's no such option, as 16.x is removed with the upgrade to Proxmox 9. I wonder if it is possible to get it back, or are there some restrictions on getting a combination of Proxmox 9 and 16.9 to work together?

**Comment by anomixer** [comment]
Hi Guys,

I've updated the script to v1.5 which is a major enhanced release including Proxmox VE 7~9 support and almost all drivers (from 16.0 to 19.1) included. But remember, not all combinations may work! Try at your own risk!

**Comment by ivan-danilov** [comment]
I see the same-named drivers in https://alist.homelabproject.cc/foxipan/vGPU/16.9/NVIDIA-GRID-Linux-KVM-535.230.02-539.19/Host_Drivers as well as 16.10, 16.11, and 16.12 added just 5 days ago. Does the 16 family of drivers still receive updates?..

**Comment by ivan-danilov** [comment]
When I updated two places in proxmox-installer.sh with URLs from alist.homelabproject.cc, it worked fine. The only perplexing message comes from [line 1524](https://github.com/anomixer/proxmox-vgpu-installer/blob/main/proxmox-installer.sh#L1524) about an unknown driver, but it seems to be expected given the code that only recognizes the 4 versions that were there in 1.4.

Also, I'd suggest prompting a reboot after the second step finishes as well. In my case, `mdevctl types` gave no output until the reboot. Which is OK for driver install, but might make the experience better for the newcomers.

Would you like me to make a PR with URL updates?

**Comment by ivan-danilov** [comment]
On the guest system Ubuntu 24.04.3, I also had trouble installing DKMS guest drivers: gcc gave compilation errors. When I tried to use guest drivers from [16.11 line](https://alist.homelabproject.cc/foxipan/vGPU/16.11/NVIDIA-GRID-Linux-KVM-535.261.04-535.261.03-539.41/Guest_Drivers), things just worked. I don't have a patch for 16.11 host drivers, so I basically have 16.9 on the host and 16.11 in the guest. Not sure if it is a good idea, but things seem to function without errors so far.
